steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA', '.']

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/manifest-verve-429713-s3/locations/asia-east1/workerPools/fastlevel'